"""OLENT-lite emitter: scenario narrative + frontmatter → machine YAML.

Reads ``overlay/narratives/scenarios/<id>/narrative.md``, parses the YAML
frontmatter block (between the two ``---`` fences), and writes the
emitted scenario YAML to
``overlay/narratives/scenarios/<id>/_emitted/scenario.yaml``.

This is intentionally narrow: it does *not* parse the prose body, it does
not regenerate the canonical catalogs, and it does not validate against
them (that's ``validate_canonical.py``). It only:

1. Splits frontmatter from prose
2. Validates the frontmatter is a YAML mapping with required fields
3. Augments with a ``narrative_hash`` (sha256 of the prose) so downstream
   consumers can detect prose drift without re-parsing
4. Writes the result to disk with a comment header pointing back at the
   source

Usage::

    python overlay/tools/emit_scenarios.py space_command_launch
    python overlay/tools/emit_scenarios.py --all
    python overlay/tools/emit_scenarios.py --help

Requires::

    pip install pyyaml
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path
from typing import Optional

try:
    import yaml
except ImportError:
    sys.stderr.write("pyyaml required: pip install pyyaml\n")
    sys.exit(2)


OVERLAY_ROOT = Path(__file__).resolve().parent.parent
NARRATIVES_DIR = OVERLAY_ROOT / "narratives" / "scenarios"

# Required keys in the frontmatter block. Anything else is passed through
# untouched. Keep this set tight — the scenario module reads from the
# emitted YAML and unexpected silent omissions would make debugging hard.
REQUIRED_FRONTMATTER_KEYS = (
    "id",
    "title",
    "voice",
    "persona_prompt",
    "switch_labels",
)


def log(msg: str) -> None:
    """Log to stderr — keeps stdout clean for any future pipe usage."""
    sys.stderr.write(f"[emit] {msg}\n")


def split_frontmatter(text: str) -> tuple[dict, str]:
    """Split a Markdown file with YAML frontmatter into (frontmatter, body).

    The frontmatter block must be the very first content of the file,
    fenced by ``---`` on its own line at start and end.
    """
    if not text.startswith("---\n") and not text.startswith("---\r\n"):
        raise ValueError("file does not begin with --- frontmatter fence")
    # Drop the opening fence and search for the closing fence.
    rest = text.split("\n", 1)[1]
    if "\n---\n" not in rest and "\n---\r\n" not in rest:
        raise ValueError("no closing --- frontmatter fence found")
    fm_text, body = rest.split("\n---\n", 1) if "\n---\n" in rest else rest.split(
        "\n---\r\n", 1)
    fm = yaml.safe_load(fm_text) or {}
    if not isinstance(fm, dict):
        raise ValueError("frontmatter is not a YAML mapping")
    return fm, body


def validate_frontmatter(fm: dict, scenario_id: str) -> list[str]:
    """Return a list of error strings (empty if all required keys present)."""
    errors: list[str] = []
    for key in REQUIRED_FRONTMATTER_KEYS:
        if key not in fm:
            errors.append(f"missing required key: {key!r}")
    declared_id = fm.get("id")
    if declared_id and declared_id != scenario_id:
        errors.append(
            f"frontmatter id={declared_id!r} disagrees with directory "
            f"{scenario_id!r}"
        )
    labels = fm.get("switch_labels") or []
    if not isinstance(labels, list) or len(labels) != 10:
        errors.append(
            f"switch_labels must be a list of exactly 10 entries, got "
            f"{type(labels).__name__} len={len(labels) if isinstance(labels, list) else 'n/a'}"
        )
    return errors


def emit_scenario(scenario_id: str, *, dry_run: bool = False) -> Path:
    """Read narrative.md, write _emitted/scenario.yaml. Return emitted path."""
    scenario_dir = NARRATIVES_DIR / scenario_id
    narrative_path = scenario_dir / "narrative.md"
    if not narrative_path.exists():
        raise FileNotFoundError(f"no narrative at {narrative_path}")

    text = narrative_path.read_text(encoding="utf-8")
    fm, body = split_frontmatter(text)

    errors = validate_frontmatter(fm, scenario_id)
    if errors:
        for err in errors:
            log(f"ERROR {scenario_id}: {err}")
        raise ValueError(f"{scenario_id}: {len(errors)} frontmatter error(s)")

    narrative_hash = hashlib.sha256(body.encode("utf-8")).hexdigest()
    emitted = dict(fm)
    emitted["narrative_hash"] = narrative_hash
    emitted["_source"] = str(narrative_path.relative_to(OVERLAY_ROOT).as_posix())
    emitted["_emitter"] = "overlay/tools/emit_scenarios.py"

    out_dir = scenario_dir / "_emitted"
    out_path = out_dir / "scenario.yaml"

    if dry_run:
        log(f"DRY-RUN would write {out_path}")
        return out_path

    out_dir.mkdir(parents=True, exist_ok=True)
    header = (
        "# AUTOGENERATED by overlay/tools/emit_scenarios.py — do not edit\n"
        f"# Source: {emitted['_source']}\n"
        f"# Hash of prose body: {narrative_hash[:12]}...\n"
        "\n"
    )
    out_path.write_text(
        header + yaml.safe_dump(emitted, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )
    log(f"wrote {out_path.relative_to(OVERLAY_ROOT).as_posix()}")
    return out_path


def discover_scenarios() -> list[str]:
    """All scenario subdirectories under narratives/scenarios."""
    if not NARRATIVES_DIR.exists():
        return []
    return sorted(
        p.name for p in NARRATIVES_DIR.iterdir()
        if p.is_dir() and (p / "narrative.md").exists()
    )


def main(argv: Optional[list[str]] = None) -> int:
    ap = argparse.ArgumentParser(
        description="Emit machine YAML from a scenario narrative.md frontmatter.",
    )
    ap.add_argument("scenario", nargs="?", default=None,
                    help="scenario id (directory name under narratives/scenarios/)")
    ap.add_argument("--all", action="store_true",
                    help="emit every scenario found under narratives/scenarios/")
    ap.add_argument("--list", action="store_true",
                    help="list discovered scenarios and exit")
    ap.add_argument("--dry-run", action="store_true",
                    help="don't write, just report what would be written")
    args = ap.parse_args(argv)

    if args.list:
        for sid in discover_scenarios():
            print(sid)
        return 0

    if not args.scenario and not args.all:
        ap.error("provide a scenario id or pass --all")

    ids: list[str]
    if args.all:
        ids = discover_scenarios()
        if not ids:
            log("no scenarios with narrative.md found")
            return 1
    else:
        ids = [args.scenario]

    failures = 0
    for sid in ids:
        try:
            emit_scenario(sid, dry_run=args.dry_run)
        except (FileNotFoundError, ValueError) as exc:
            log(f"FAILED {sid}: {exc}")
            failures += 1
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
